import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useEffect } from 'react';
import { useLiff } from 'use-line-liff';

export default function Home() {
   const { liff} = useLiff();
  useEffect(() => {
   if (!liff) return;
   if(!liff.isLoggedIn()) {
     liff.login();
   }
  })
 return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        test
     </main>

    </div>
  )
}
